# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # compile typescript
      - run: npm run clean
      - run: npm run compile

      # run tests!
      - run: npm run test

      # install cli globally
      - run: mkdir /home/circleci/packed-modules
      - run:
          name: Pack cli-core
          command: |
            cd packages/cli-core 
            npm install
            npm pack
            mv toucansam-bpl-cli-core-1.0.8-alpha.0.tgz /home/circleci/packed-modules
      - run:
          name: Pack CLI
          command: |
            cd packages/cli
            sed -i 's/file:..\/cli-core/\/home\/circleci\/packed-modules\/toucansam-bpl-cli-core-1.0.8-alpha.0.tgz/g' package.json
            npm install
            npm pack
            ls
      - run:
          name: Install CLI
          command: |
            ls
            sudo npm install -g /home/circleci/repo/packages/cli/bpl-cli-1.0.8-alpha.0.tgz

      - run: bpl hello
